### ISSUE TITLE
Comentarios refactorización Akka stream

### ISSUE THREAD

**Issue by jserranohidalgo** [PumPumDev/SparkLoLData#4]
- [x] Sbt multi-project. Hay que diferenciar entre el proyecto de descarga de datos, el de queries basadas en Scala colletions, y el de queries Spark (al menos). Ref: https://www.scala-sbt.org/1.x/docs/Multi-Project.html

- [x] Limpiar ficheros, e.g. `MainTest.scala`

- [x] package `usefull` => `utils`. La función `execTime` debería venir aquí. `Region.scala` no es una utilidad, pertenece al modelo de datos. 

- [x] Puedes poner todas las propiedades en `application.conf`, incluidas las credenciales, uris, etc. Para las uris te puedes fijar [aquí](https://github.com/DanielaSfregola/twitter4s/blob/master/src/main/scala/com/danielasfregola/twitter4s/util/Configurations.scala#L11)

- [x] El `Materializer` se obtiene implícitamente, comenta:
```scala
 // implicit val materializer: Materializer = Materializer(system)
```

- [x] No entiendo exactamente la información que genera por consola el programa principal: 
```scala
  val results = for {
    // Uncomment this lane to update de data from RIOT API
    //_ <- updateChallengerData(Region.getAllRegions, apiKeysAvailable, outputPath)
    playersData <- getChallengerPlayers(outputPath)
    matchesData <- getChallengerMatches(outputPath)
  } yield (playersData, matchesData)
```
¿es un resumen de la información descargada/disponible, o *toda* la información? Tienes que documentar en el README el uso concreto del main.

- [x] "// Is this the correct use of for-comprehension?" Si quieres que los futuros ejecuten concurrentemente no se pueden encadenar en un flatmap, que es a lo que se traduce la for-comprehension (más un map en el último paso). Porque el segundo futuro no se instancia hasta que tenemos la respuesta del primero: https://alvinalexander.com/scala/how-use-multiple-scala-futures-in-for-comprehension-loop/

- [ ]  el método `getDataFromAPI` pertenecería a utils si no fuera porque recibe como argumento la región, que es algo del dominio (en utils se encuentran utilidades que podrían estar perfectamente en otros proyectos, por lo que no deben tener referencias a entidades de tu aplicación). Por lo mismo, algunas utilidades de ficheros (`writeData`) no deberían hacer referencia a la región (y en este caso, parece que no se utiliza, de hecho). Los métodos de `StreamComponents` también deberían ir a utilidades, sin referencia a la región. 

- [ ] La parte de Streaming debería ser más grande. Ahora está acotada a `getDataFromAPI`, pero debería llegar hasta `updateChallengerData`. Es decir, la ejecución del `RunnableGraph` en términos de `Future` se debería realizar en el programa principal. Esto te permitirá librarte del `Future.foldLeft` y hacer un programa de streaming más comprensible e idiomático. Para conseguir esto, el `loadData` tendrá que devolver un `Source`, claro.

- [x] Te añado aquí también tu "TODO: Check the data is available and get if it is not "

- [ ] Unas estadísticas sobre la eficiencia de las descargas estaría bien, para comparar los resultados con las limitaciones de la API (20 requests every 1 seconds(s)/100 requests every 2 minutes(s))

**Comment by PumPumDev** [comment]
En el último commit en la PR #3, he hecho algunas modificaciones de las que me comentas: ee2a65434cc016e56583e3dc6a9c5c9a2d8da8a2

He decidido separarlo en 5 módulos (subproyectos de SBT):

- Cliente API: Para la descarga de datos
- Scala Queries: Para las queries usando la libreria Collections de Scala
- Spark Queries: Para las queries usando Spark (Dataset y Dataframe)
- Utils: Acumulan funcionalidad básica que debe ser conocida por todos los módulos (ej: carga de datos)
- Models: Contiene los objetos de negocio, debe ser conocido por los primeros 3 módulos.

Aun así hay algunos puntos de los señalados que me gustaría comentarte.

**Comment by jserranohidalgo** [comment]
Mañana lo tengo complicado, pero creo que le podré echar un vistazo. El martes por la mañana podemos quedar sin problemas, ¿qué tal a las 12?

**Comment by PumPumDev** [comment]
Sí, para el martes iría a esa hora me iría bien.

**Comment by PumPumDev** [comment]
Acabo de subir los cambios referentes a la ampliación de la parte Stream y la posibilidad de obtener mediciones de rendimiento de la API en el siguiente commit:
b898c5ee5c30bc92605bf25c3dca9c1942067969
